name: docker

on: [push, pull_request]

jobs:
  build:
    name: Build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.1

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
          registry: docker.pkg.github.com
          repository: pollxy/pruxy
          tag_with_ref: true

        
